_BASE_: base.yaml
MODEL:
#  WEIGHTS: "model_final_3c8ec9.pkl"
  META_ARCHITECTURE: "UniDVPS"
  SEM_SEG_HEAD:
    NAME: "UnifiedDecoderHead"
    IGNORE_VALUE: 255000
    NUM_CLASSES: 19
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  UNIFIED_FORMER:
    TRANSFORMER_DECODER_NAME: "UnifiedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    MATCHER: "dvps_matcher"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 491520
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
    DEPTH_DIM: 256
    DEPTH_MAX: 88.
    SILOG_WEIGHT: 3.0
    REL_SQR_WEIGHT: 3.0
    REL_ABS_WEIGHT: 3.0
INPUT:
  SAMPLING_FRAME_NUM: 1
